const itemList = {
    null: {
        "name": "Empty Item Slot",
        "type": "Empty",
        "icon": "",
        "info": "",
        "comps": "",

    },
//Support Items
    "": {
        "name": "Aegis of the Legion",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",

    },
    "": {
        "name": "Banshee's Veil",
        "type": "Support",
        "icon": "",
    },
    "": {
        "name": "Chalice of Power",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Crest of Cinders",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Locket of the Iron Solari",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Needlessly Big Gem",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Obsidian Cleaver",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Randuin's Omen",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Shroud of Stillness",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Virtue of the Martyr",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Zeke's Herald",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Zephyr",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
    "": {
        "name": "Zz'Rot Portal",
        "type": "Support",
        "icon": "",
        "info": "",
        "comps": "",
    },
//Normal Items
    "TFT_Item_Chalice": {
        "name": "Adaptive Helm",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Tear", "Cloak"],
    },
    "TFT_Item_Morellonomicon": {
        "name": "Morellonomicon",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Belt"],
    },
    "TFT_Item_JeweledGauntlet": {
        "name": "Jeweled Gauntlet",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Glove"],
    },
    "TFT_Item_Bloodthirster": {
        "name": "Bloodthirster",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Cloak"],
    },
    "TFT_Item_BrambleVest": {
        "name": "Bramble Vest",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Chain Vest", "Chain Vest"],
    },
    "TFT_Item_SeraphsEmbrace": {
        "name": "Blue Buff",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Tear", "Tear"],
    },
    "TFT_Item_LocketOfTheIronSolari": {
        "name": "Crownguard",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Chain Vest"],
    },
    "TFT9_Item_CrownOfDemacia": {
        "name": "Crown of Demacia",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_DragonsClaw": {
        "name": "Dragon's Claw",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Cloak", "Cloak"],
    },
    "TFT_Item_Zephyr": {
        "name": "Evenshroud",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Cloak", "Belt"],
    },
    "TFT_Item_FrozenHeart": {
        "name": "Protector's Vow",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Tear", "Chain Vest"],
    },
    "TFT_Item_ForceOfNature": {
        "name": "Tactician's Crown",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Spatula", "Spatula"],
    },
    "TFT_Item_MadredsBloodrazor": {
        "name": "Giant Slayer",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Bow"],
    },
    "TFT_Item_PowerGauntlet": {
        "name": "Guardbreaker",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Belt", "Glove"],
    },
    "TFT_Item_GuardianAngel": {
        "name": "Edge of Night",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Chain Vest"],
    },
    "TFT_Item_GuinsoosRageblade": {
        "name": "Guinsoo's Rageblade",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Bow"],
    },
    "TFT_Item_UnstableConcoction": {
        "name": "Hand of Justice",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Tear", "Glove"],
    },
    "TFT_Item_HextechGunblade": {
        "name": "Hextech Gunblade",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Rod"],
    },
    "TFT_Item_InfinityEdge": {
        "name": "Infinity Edge",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Glove"],
    },
    "TFT_Item_IonicSpark": {
        "name": "Ionic Spark",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Cloak"],
    },
    "TFT_Item_GargoyleStoneplate": {
        "name": "Gargoyle Stoneplate",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Cloak", "Chain Vest"],
    },
    "TFT_Item_IonicSpark": {
        "name": "Last Whisper",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Glove"],
    },
    "TFT_Item_Deathblade": {
        "name": "Deathblade",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Sword"],
    },
    "TFT_Item_ArchangelsStaff": {
        "name": "Archangel's Staff",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Tear"],
    },
    "Masterwork Upgrade": {
        "name": "Masterwork Upgrade",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_TitanicHydra": {
        "name": "Nashors' Tooth",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Belt"],
    },
    "TFT_Item_Shroud": {
        "name": "Night Harvester",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Chain Vest", "Glove"],
    },
    "TFT_Item_Quicksilver": {
        "name": "Quicksilver",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Cloak", "Glove"],
    },
    "TFT_Item_RabadonsDeathcap": {
        "name": "Rabadon's Deathcap",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Rod", "Rod"],
    },
    "TFT_Item_RapidFireCannon": {
        "name": "Rapid Firecannon",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Bow"],
    },
    "TFT_Item_Redemption": {
        "name": "Redemption",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Tear", "Belt"],
    },
    "TFT_Item_RunaansHurricane": {
        "name": "Runaan's Hurricane",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Cloak"],
    },
    "Scroll of Knowledge": {
        "name": "Scroll of Knowledge",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_SpearOfShojin": {
        "name": "Spear of Shojin",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Tear"],
    },
    "TFT_Item_StatikkShiv": {
        "name": "Statikk Shiv",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Tear"],
    },
    "TFT_Item_ZekesHerald": {
        "name": "Sterak's Gage",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Sword", "Belt"],
    },
    "TFT_Item_RedBuff": {
        "name": "Sunfire Cape",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Belt", "Chain Vest"],
    },
    "The Darkin Blade": {
        "name": "The Darkin Blade",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_ThiefsGloves": {
        "name": "Thief's Gloves",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Glove", "Glove"],
    },
    "TFT_Item_TitansResolve": {
        "name": "Titan's Resolve",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Bow", "Chain Vest"],
    },
    "TFT_Item_WarmogsArmor": {
        "name": "Warmog's Armor",
        "type": "Normal",
        "icon": "",
        "info": "",
        "comps": ["Belt", "Belt"],
    },

//Components
    "TFT_Item_NegatronCloak": {
        "name": "Cloak",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_GiantsBelt": {
        "name": "Belt",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_TearOfTheGoddess": {
        "name": "Tear",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_RecurveBow": {
        "name": "Bow",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_NeedlesslyLargeRod": {
        "name": "Rod",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_NeedlesslyLargeRod": {
        "name": "Chain Vest",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_BFSword": {
        "name": "Sword",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_Spatula": {
        "name": "Spatula",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT_Item_SparringGloves": {
        "name": "Glove",
        "type": "Component",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },

//Trait Items
    "TFT9_Item_StrategistEmblem": {
        "name": "Strategist Emblem",
        "type": "",
        "icon": "Emblem",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_SlayerEmblem": {
        "name": "Slayer Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_BrawlerEmblem": {
        "name": "Bruiser Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_BastionEmblem": {
        "name": "Bastion Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_ArmorcladEmblem": {
        "name": "Juggernaut Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_DemaciaEmblem": {
        "name": "Demacia Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_VoidEmblem": {
        "name": "Void Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_IoniaEmblem": {
        "name": "Ionia Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_SorcererEmblem": {
        "name": "Sorcerer Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_PreserverEmblem": {
        "name": "Invoker Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_ZaunEmblem": {
        "name": "Zaun Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_TargonEmblem": {
        "name": "Targon Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_RogueEmblem": {
        "name": "Rogue Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_TrickshotEmblem": {
        "name": "Gunner Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_ChallengerEmblem": {
        "name": "Challenger Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_PiltoverEmblem": {
        "name": "Piltover Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_NoxusEmblem": {
        "name": "Noxus Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_ShurimaEmblem": {
        "name": "Shurima Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_Item_FreljordEmblem": {
        "name": "Freljord Emblem",
        "type": "Emblem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
//Artifact Items
    "": {
        "name": "",
        "type": "Artifact",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
//Radiant Items
    "TFT5_Item_BrambleVestRadiant": {
        "name": "Rosethorn Vest",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT5_Item_ChaliceOfPowerRadiant": {
        "name": "Jak'sho the Protean",
        "type": "Radiant",
        "icon": "",
        "info": "formerly chalice",
        "comps": ["", ""],
    },
    "TFT5_Item_ZekesHeraldRadiant": {
        "name": "Sterak's Megashield",
        "type": "Radiant",
        "icon": "",
        "info": "formerly zeke's",
        "comps": ["", ""],
    },
    "TFT5_Item_GargoyleStoneplateRadiant": {
        "name": "Dvarapala Stoneplate",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT5_Item_TitansResolveRadiant": {
        "name": "Titan's Vow",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT5_Item_GuardianAngelRadiant": {
        "name": "Brink of Dawn",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_IonicSparkRadiant": {
        "name": "Covalent Spark",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_DragonsClawRadiant": {
        "name": "Dragon's Will",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_ShroudOfStillnessRadiant": {
        "name": "Midnight Reaper",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_RabadonsDeathcapRadiant": {
        "name": "Rabadon's Ascended Deathcap",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_MorellonomiconRadiant": {
        "name": "More More-ellonomicon",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_ArchangelsStaffRadiant": {
        "name": "Urf-Angel's Staff",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_InfinityEdgeRadiant": {
        "name": "Zenith Edge",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_DeathbladeRadiant": {
        "name": "Luminous Deathblade",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_SunfireCapeRadiant": {
        "name": "Sunlight Cape",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_FrozenHeartRadiant": {
        "name": "Bulwark's Oath",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_RedemptionRadiant": {
        "name": "Absolution",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_BloodthirsterRadiant": {
        "name": "Blessed Bloodthirster",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_HandOfJusticeRadiant": {
        "name": "Fist of Fairness",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_GuinsoosRagebladeRadiant": {
        "name": "Guinsoo's Reckoning",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_RunaansHurricaneRadiant": {
        "name": "Runaan's Tempest",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_TrapClawRadiant": {
        "name": "Stridebreaker",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_WarmogsArmorRadiant": {
        "name": "Warmog's Pride",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_JeweledGauntletRadiant": {
        "name": "Glamorous Gaunlet",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_HextechGunbladeRadiant": {
        "name": "Hextech Lifeblade",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_BlueBuffRadiant": {
        "name": "Blue Blessing",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_SpearOfShojinRadiant": {
        "name": "Spear of Hirana",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_QuicksilverRadiant": {
        "name": "Quickestsilver",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_LastWhisperRadiant": {
        "name": "Eternal Whisper",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_ZzRotPortalRadiant": {
        "name": "Nashors' Tooth Radiant",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_ThiefsGlovesRadiant": {
        "name": "Rascal's Gloves",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_GiantSlayerRadiant": {
        "name": "Demon Slayer",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_RapidFirecannonRadiant": {
        "name": "Rapid Lightcannon",
        "type": "Radiant",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    }, 
    "TFT5_Item_ZephyrRadiant": {
        "name": "Equinox",
        "type": "Radiant",
        "icon": "",
        "info": "Radiant evenshroud",
        "comps": ["", ""],
    }, 
//Heimer Turret Items
    "TFT9_HeimerUpgrade_ShrinkRay": {
        "name": "Turret: Shrink Ray",
        "type": "HeimerItem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_HeimerUpgrade_MicroRockets": {
        "name": "Turret: Micro Rockets",
        "type": "HeimerItem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_HeimerUpgrade_Goldification": {
        "name": "Turret: Goldification",
        "type": "HeimerItem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
    "TFT9_HeimerUpgrade_SelfRepair": {
        "name": "Turret: Self Repair",
        "type": "HeimerItem",
        "icon": "",
        "info": "",
        "comps": ["", ""],
    },
}

module.exports = itemList