const ryzeInfo = {
    BandleCity: "Ryze creates a portal to Bandle City underneath a random unit on your bench. After a brief delay, they arrive on the battlefield with bonus mana.",
    Demacia: "Ryze creates a portal to Demacia underneath a cluster of injured allies, granting Shield for 2 seconds. If an ally leaves the safety of the portal, they are healed for Health. When the portal expires, enemies within are dealt magic damage.",
    Freljord: "Ryze creates a portal to the Freljord underneath a random group of enemies for 3 seconds. The freezing winds deal magic damage to enemies within two hexes over the duration and apply Permafrost, a permanent Chill (Reduce Attack Speed by 30%). If enemies are already affected by Permafrost, they are instead Stunned for the duration.",
    Ionia: "Ryze creates a portal to Ionia, summoning forth a Spirit Tree that affects the closest units. Allies are invigorated, gaining Attack Speed for 6 seconds and restoring Health over the duration. Enemies are pacified, causing them to dance.",
    Noxus: "Ryze creates a portal to Noxus' armory that spews out a torrent of weapons and armor, granting completed items to random allies with open slots, and throwing Axes towards random enemies that deal magic damage each. If any ally would recieve an item while all slots are full, they instead gain a stacking 40% damage increase for the rest of combat.",
    Piltover: "Ryze summons a portal to Piltover that launches out an enforcer grenade towards his target, dealing magic damage to enemies within two hexes and creating a containment area for seconds. Enemies are unable to leave the area, and of the damage dealt to them is also dealt to all other enemies within.",
    ShadowIsles: "Ryze creates a portal to the Shadow Isles, reclaiming lost ally's souls. They return to the battlefield, with % of their maximum Health. If no allies have died yet, the portal remains open, waiting for an ally to die. Ryze cannot resurrect himself.",
    Shurima: "Ryze creates a portal to Shurima, summoning a gigantic sand tornado that travels across the battlefield, dealing magic damage to enemies hit and knocking them up briefly.The tornado has chance to unearthed burried treasures and gold as it travels.",
    Targon: "Ryze creates a portal to the skies above Mount Targon that beckons his target. After a few seconds, they descend from the heavens as a meteor towards the largest cluster of enemies, dealing % of the the initial target's maximum Health as magic damage and knocking up enemies in the epicenter.",
    Zaun: "Open portals to Zuan, causing hired guns to fire a torrent of munitions at a nearby enemy that deal magic damage and apply 50% Wound, 40% Shred, and 40% Sunder for 6 seconds. The more gold you have, the more power the portals become. 25 Gold: +1 Portal. Portals fire a rocket that deals 50% damage in a one-hex radius 50 Gold: Double the portals. Summon +2 additional portals for every 15 Gold more.",
}

