set9traits = {
    "Demacia": ["Kayle", "Poppy", "Galio", "Garen", "Sona", "Jarvan", "Lux"],
    "Freljord": ['Ashe','Lissandra','Sejuani'],
    "Ionia": ['Irelia', 'Jhin', 'Sett', 'Zed', 'Karma', 'Shen','Yasuo','Ahri'],
    'Noxus': ['Cassiopeia', 'Samira', 'Kled', 'Swain', 'Darius', 'Katarina', 'Sion'],
    'Piltover': ['Orianna', 'Vi','Ekko', 'Jayce', 'Heimerdinger'],
    'Shadow Isles': ['Maokai', 'Veigo', 'Kalista', 'Gwen', 'Senna'],
    'Shurima': ['Cassiopeia', 'Renekton', 'Taliyah', 'Akshan', 'Azir', 'Nasus', 'Ksante'],
    'Targon': ['Soraka', 'Taric', 'Aphelios'],
    'Void': ['Chogath', 'Malzahar', 'Kassadin', 'Reksai', 'Velkoz', 'Kaisa', 'Belveth'],
    'Yordle': ['Poppy', 'Tristana', 'Kled', 'Teemo', 'Heimerdinger'],
    'Zaun': ['Jinx', 'Warwick', 'Ekko', 'Urgot', 'Zeri'],
    'Bastion': ['Maokai', 'Poppy', 'Kassadin', 'Taric', 'Shen', 'Ksante'],
    'Bruiser': ['Chogath', 'Renekton', 'Vi', 'Reksai', 'Sejuani', 'Sion'],
    'Challenger': ['Irelia', 'Samira', 'Warwick', 'Kalista', 'Kaisa', 'Yasuo'],
    'Deadeye': ['Jhin', 'Ashe', 'Akshan', 'Aphelios', 'Urgot'],
    'Gunner': ['Tristana', 'Jinx', 'Jayce', 'Zeri', 'Senna'],
    'Invoker': ['Cassiopeia', 'Galio', 'Soraka', 'Karma', 'Lissandra', 'Shen'],
    'Juggernaut': ['Sett','Warwick', 'Darius', 'Garen', 'Nasus', 'Aatrox'],
    'Multicaster': ['Taliyah', 'Teemo', 'Sona', 'Velkoz'],
    'Rogue': ['Veigo', 'Zed', 'Ekko', 'Katarina'],
    'Slayer': ['Kayle', 'Kled', 'Zed', 'Gwen', 'Aatrox'],
    'Sorcerer': ['Malzahar', 'Orianna', 'Swain', 'Taric', 'Velkoz', 'Lux', 'Ahri'],
    'Strategist': ['Swain', 'Teemo', 'Azir', 'Jarvan'],

}

