const set9traits = {
    "Demacia": ["Kayle", "Poppy", "Galio", "Garen", "Sona", "Jarvan IV", "Lux"],
    "Freljord": ['Ashe','Lissandra','Sejuani'],
    "Ionia": ['Irelia', 'Jhin', 'Sett', 'Zed', 'Karma', 'Shen','Yasuo','Ahri'],
    'Noxus': ['Cassiopeia', 'Samira', 'Kled', 'Swain', 'Darius', 'Katarina', 'Sion'],
    'Piltover': ['Orianna', 'Vi','Ekko', 'Jayce', 'Heimerdinger'],
    'Shadow Isles': ['Maokai', 'Veigo', 'Kalista', 'Gwen', 'Senna'],
    'Shurima': ['Cassiopeia', 'Renekton', 'Taliyah', 'Akshan', 'Azir', 'Nasus', "K'Sante"],
    'Targon': ['Soraka', 'Taric', 'Aphelios'],
    'Void': ["Cho'Gath", 'Malzahar', 'Kassadin', 'Reksai', 'Velkoz', "Kai'Sa", 'Belveth'],
    'Yordle': ['Poppy', 'Tristana', 'Kled', 'Teemo', 'Heimerdinger'],
    'Zaun': ['Jinx', 'Warwick', 'Ekko', 'Urgot', 'Zeri'],
    'Bastion': ['Maokai', 'Poppy', 'Kassadin', 'Taric', 'Shen', "K'Sante"],
    'Bruiser': ["Cho'Gath", 'Renekton', 'Vi', 'Reksai', 'Sejuani', 'Sion'],
    'Challenger': ['Irelia', 'Samira', 'Warwick', 'Kalista', "Kai'Sa", 'Yasuo'],
    'Deadeye': ['Jhin', 'Ashe', 'Akshan', 'Aphelios', 'Urgot'],
    'Gunner': ['Tristana', 'Jinx', 'Jayce', 'Zeri', 'Senna'],
    'Invoker': ['Cassiopeia', 'Galio', 'Soraka', 'Karma', 'Lissandra', 'Shen'],
    'Juggernaut': ['Sett','Warwick', 'Darius', 'Garen', 'Nasus', 'Aatrox'],
    'Multicaster': ['Taliyah', 'Teemo', 'Sona', "Vel'Koz"],
    'Rogue': ['Veigo', 'Zed', 'Ekko', 'Katarina'],
    'Slayer': ['Kayle', 'Kled', 'Zed', 'Gwen', 'Aatrox'],
    'Sorcerer': ['Malzahar', 'Orianna', 'Swain', 'Taric', 'Velkoz', 'Lux', 'Ahri'],
    'Strategist': ['Swain', 'Teemo', 'Azir', 'Jarvan IV'],
    1: ['Samira', 'Malzahar', 'Kayle', "Cho'Gath", 'Cassiopeia', 'Maokai', 'Irelia', 'Poppy', 'Veigo', 'Orianna', 'Jhin', 'Renekton'],
    2: ['Soraka', 'Ashe', 'Swain', 'Kled', 'Zed', 'Kassadin', 'Jinx', 'Warwick', 'Galio', 'Sett', 'Taliyah', 'Teemo', 'Vi'],
    3: ['Karma', 'Katarina', 'Darius', 'Lissandra', 'Taric', "Vel'Koz", "Rek'Sai", 'Kalista', 'Sona','Akshan', 'Ekko', 'Jayce', 'Garen'],
    4: ['Gwen', 'Shen', "Jarvan IV", 'Sejuani', 'Yasuo', "Kai'Sa", 'Zeri', 'Aphelios', 'Lux', 'Urgot', 'Nasus', 'Azir'],
    5: ['Ryze', 'Aatrox', 'Heimerdinger', 'Senna', 'Ahri', 'Sion', "Bel'Veth", "K'Sante"],
}

module.exports = set9traits
